### ISSUE TITLE
Container "gitea" is not stopped by "docker-compose down"

### ISSUE THREAD

**Issue by wagst** [intel/Edge-Software-Provisioner#1]
As far as i have seen, the run.sh script starts all the containers listed in the docker-compose.yml file, except the gitea container, which is started by a subscript.
So when i want to stop or deactivate the ESP, i always have to stop the "gitea" container manually.

I would suggest that all running containers should be stopped by "docker-compose down".

**Comment by brod-intel** [comment]
Thank you for the suggestion, v1.6 is going to be released shortly that pulls gitea in to docker-compose.yml and run.sh.  v2.0 will fix it further with an ESP core service manager to make services are started and stopped etc.

**Comment by brod-intel** [comment]
ESP v1.6 has been released with the "gitea" container managed by docker-compose.
