### ISSUE TITLE
Clear Linux Desktop profile is not installed completely.

### ISSUE THREAD

**Issue by ionutnechita** [intel/Edge-Software-Provisioner#10]
Hi ESP Team,

I use this profile for install Clear Linux OS.
But i view one issue under deployment.

Manifest.Mom.tar is not downloading in chroot.
I think this is cause not appear file /etc/resolv.conf in chroot.

>> swupd bundle-add desktop
swupd tool not working. MoM file is not downloading.

Profile:
  - git_remote_url: https://github.com/intel/rni-profile-base-clearlinux.git
    profile_branch: desktop
    profile_base_branch: master
    git_username: ""
    git_token: ""
    name: clearlinux-desktop_profile
    custom_git_arguments: --depth=1

**Comment by brod-intel** [comment]
Please contribute these changes to https://github.com/intel-collab/applications.provisioning.esp.profiles.clearlinux
