### ISSUE TITLE
ESP services build (build.sh) fails when executed inside a container

### ISSUE THREAD

**Issue by vinaysha11983741** [intel/Edge-Software-Provisioner#7]
ESP services buid(build.sh) fails when executed inside a container
 While executing build.sh inside a docker container "apk update" inside alpine container fails since proxy parameters are not passed to the alpine container hence http://dl-cdn.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz is not accessible

**Comment by brod-intel** [comment]
This has been fixed already and a patch will be released very soon.
