### ISSUE TITLE
Yocto Embedded Linux with ESP - Guide and Examples

### ISSUE THREAD

**Issue by ionutnechita** [intel/Edge-Software-Provisioner#8]
Hi ESP Team,

I saw on the documentation page that an implementation with Yocto or a Yocto derivative would be possible.
In my case I would like to deploy with AGL (Automotive Grade Linux) on my development target.
I would like an example in this case or if you can create a page for this aspect.

Thanks.

**Comment by brod-intel** [comment]
Please setup a meeting with me and I will walk you through it.
